name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
      - uses: actions/upload-artifact@v2
        with: 
          name: built
          if-no-files-found: error
          path: |
            dist
            action.yml
  test: # make sure the action works on a clean machine without building
    runs-on: ${{ matrix.on }}
    needs: [build]
    strategy:
      matrix: 
        version:
          - 1.16.5-36.1.0
          - 1.12.2-14.23.5.2855
          - 1.7.10-10.13.4.1614-1.7.10
        on:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: built
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: ./
        with:
          version: ${{ matrix.version }}
  conclude:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - build
      - test
    steps:
      - name: Conclude Tests
        env: { NEEDS: "${{ toJSON(needs) }}" }
        run: |
          echo "$NEEDS" | jq -c '. | to_entries[] | [.key, .value.result]'
          echo "$NEEDS" | jq -e '. | all(.result == "success")' > /dev/null
